from django.db import models
from django.contrib import admin

class Hotel_description(models.Model):
    hotel_name = models.CharField("Название отеля", max_length=120)
    category = models.CharField("Звездность", max_length=150, choices=(("3* ", "3* "), ("4* ", "4* "), ("5* ", "5* "), ("- ", "- ")), blank=True)
    text_block = models.TextField("Комментарии", blank=True)
    email_block = models.EmailField("E-mail")
    hotel_images = models.ImageField("Загрузить фото", blank=True)
    square = models.FloatField("Площадь отеля, м", blank=True, null=True)
    adress = models.CharField("Адрес", max_length=200)
    web_site = models.URLField("Адрес сайта")
    telephone = models.CharField("Телефон", max_length=120)
    distance_to_center = models.CharField("До центра, м", max_length=120, blank=True)
    nearest_airport = models.CharField("Ближайший аэропорт", max_length=200, blank=True)
    distance_to_airport = models.CharField("До аэропорта, м", max_length=120, blank=True)
    distance_to_beach = models.FloatField("До пляжа, м", blank=True, null=True)
    construction_year = models.CharField("Год создания", max_length=5, blank=True)
    renovation_year = models.CharField("Год реновации", max_length=5, blank=True)
    meal = models.CharField("Тип питания", max_length=50, choices=(("BB", "BB"), ("HB", "HB"), ("FB", "FB"), ("All Inclusive", "All Inclusive")), blank=True)
    check_in = models.TimeField("Check in", max_length=50, blank=True, null=True)
    check_out = models.TimeField("Check out", max_length=50, blank=True, null=True)
    deposit = models.CharField("Депозит", max_length=200, blank=True)
    credit_card = models.CharField("Кредитные карты", max_length=150,
                                   choices=(("Visa", "Visa"), ("Master Card", "Master Card"), ("Dinners", "Dinners"), ("Другое (укажите)", "Другое (укажите)")),
                                   blank=True)
    credit_card_other = models.CharField("Ваш вариант", max_length=120, blank=True)

    main_building = models.FloatField("Главное здание, этажей", blank=True, null=True)
    anex_quantity = models.FloatField("Anex, корпусов", blank=True, null=True)
    anex_floors = models.FloatField("Anex, этажей", blank=True, null=True)
    villas_quantity = models.FloatField("Виллы, кол-во", blank=True, null=True)
    villas_floors = models.FloatField("Виллы, этажей", blank=True, null=True)
    other_buildings_quantity = models.FloatField("Доп. корпуса, кол-во", blank=True, null=True)
    other_buildings_floors = models.FloatField("Доп. корпуса, этажей", blank=True, null=True)

    disabled = models.BooleanField("Услуги для инвалидов", blank=True, null=True)
    pets_friendly = models.BooleanField("Размещение с домашними животными", blank=True, null=True)
    non_smoking_hotel = models.BooleanField("Курение на всей территории запрещено", blank=True, null=True)
    adults_only = models.BooleanField("Только для взрослых", blank=True, null=True)
    adults_only_age = models.FloatField("Минимальный возраст гостей (для отелей adults only)", blank=True, null=True)

    nanny = models.CharField("Услуги няни", max_length=150, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    child_chairs = models.CharField("Высокие стулья в ресторане", max_length=150, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    child_food = models.CharField("Детское меню", max_length=150, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    child_playground = models.CharField("Детская площадка", max_length=150, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    baby_cot = models.CharField("Детская кроватка в номере", max_length=150, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    child_carriage = models.CharField("Детская коляска", max_length=150, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    baby_equipment = models.CharField("Горшок, ванна, подогреватель бутылочек", max_length=150,
                                      choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    mother_corner = models.CharField("Уголок матери", max_length=150, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    child_restaurant = models.CharField("Детский ресторан", max_length=150, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    child_club = models.CharField("Детский клуб", max_length=150, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    child_club_age = models.CharField("Возраст детей, которых принимают в клубе", max_length=200, blank=True)
    child_pool = models.CharField("Детский бассейн", max_length=150, choices=(("есть", "есть"), ("нет", "нет")), blank=True)
    child_pool_quantity = models.FloatField("Количество детских бассейнов", blank=True, null=True)
    text = models.CharField("Комментарии", max_length=500, blank=True)

    total_room_numbers = models.FloatField("Общее количество номеров", null=True, blank=True)
    room_type_name = models.CharField("Название номера по контракту", max_length=300, blank=True)
    room_type_numbers = models.FloatField("Кол-во номеров этого типа", blank=True, null=True)
    room_type_building = models.CharField("В каком здании номер", max_length=120, choices=(("Главное здание", "Главное здание"),
                                                                                           ("Anex", "Anex"), ("Villa", "Villa"), ("Бунгало", "Бунгало"),
                                                    (6, "Доп корпус")), blank=True)
    room_type_view = models.CharField("Вид из номера", max_length=120, choices=(("Sea View", "Sea View"), ("Pool View", "Pool View"),
                                                                                ("Garden View", "Garden View"), ("Другое", "Другое")), blank=True)
    room_type_view_other = models.CharField("Ваш вариант", max_length=200, blank=True)
    room_type_size = models.FloatField("Размер, кв.м.", blank=True, null=True)
    room_type_beds = models.CharField("Тип кровати", max_length=200, choices=(("Double French Bed", "Double French Bed"),
                                                                              ("Double King Size Bed", "Double King Size Bed"), ("Twin bed", "Twin bed"),
                                                                              ("Другое", "Другое")), blank=True)
    room_type_beds_other = models.CharField("Ваш вариант", max_length=200, blank=True)
    connected_rooms = models.BooleanField("Cовмещенные комнаты", blank=True, null=True)
    door_rooms = models.BooleanField("Дверь между комнатами", blank=True, null=True)
    living_room = models.BooleanField("Есть гостиная", blank=True, null=True)
    room_type_max_pax = models.CharField("Макс. размещение (взр.+реб)", max_length=200, blank=True)
    room_type_extra_beds = models.CharField("Доп место для ребенка", max_length=120, choices=(("Normal Bed", "Normal Bed"),
                                                                                              ("Pull Out Chair", "Pull Out Chair"),
                                                                                              ("Pull Out Couch", "Pull Out Couch"),
                                                                                              ("Sofa", "Sofa"), ("нет", "нет")), blank=True)
    room_type_rooms = models.FloatField("Количество комнат в номере", blank=True, null=True)
    room_type_bedrooms = models.FloatField("Количество спален", blank=True, null=True)
    room_type_areas = models.CharField("Другие комнаты в номере", max_length=300, blank=True)

    shower = models.CharField("Душ/ванна", max_length=120, choices=(("душ", "душ"), ("ванна", "ванна"), ("душ и ванна", "душ и ванна")), blank=True)
    hair_dryer = models.BooleanField("Фен", blank=True, null=True)
    roba_and_slippers = models.BooleanField("Халаты и тапочки", blank=True, null=True)
    jakuzi = models.BooleanField("Джакузи", blank=True, null=True)
    mini_kitchen = models.BooleanField("Мини-кухня", blank=True, null=True)
    dishes = models.BooleanField("Тарелки и столовые приборы", blank=True, null=True)
    oven = models.BooleanField("Плита с духовкой", blank=True, null=True)
    dishwasher = models.BooleanField("Посудомоечная машина", blank=True, null=True)
    microwave = models.BooleanField("Микроволновка", blank=True, null=True)
    air_condition = models.CharField("Кондиционер", max_length=120, choices=(("центральное кондиционирование", "центральное кондиционирование"),
                                                                             ("индивидуальный кондиционер", "индивидуальный кондиционер"),
                                               ("вентилятор", "вентилятор"), ("сплит-система", "сплит-система"),
                                                                             ("без кондиционера", "без кондиционера")), blank=True)
    coffee_and_tea = models.BooleanField("Наборы для чая и кофе", blank=True, null=True)
    ketler = models.BooleanField("Чайник", blank=True, null=True)
    mini_bar = models.BooleanField("Мини-бар", blank=True, null=True)
    fridge = models.BooleanField("Холодильник", blank=True, null=True)
    tv = models.BooleanField("TV", blank=True, null=True)
    dvd = models.BooleanField("DVD", blank=True, null=True)
    telephone_in_room = models.BooleanField("Телефон", blank=True, null=True)
    tv_channels = models.FloatField("Русских каналов", blank=True, null=True)
    wi_fi = models.CharField("Wi-Fi", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    wi_fi_price = models.CharField("Wi-Fi, цена/день", max_length=120, blank=True)
    safe = models.CharField("Сейф", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    safe_price = models.CharField("Цена за сейф/день", max_length=120, blank=True)
    balcony = models.CharField("Балкон", max_length=120, choices=(("балкон", "балкон"), ("французский балкон", "французский балкон")), blank=True)
    terrace = models.BooleanField("Терраса", blank=True, null=True)
    carpet = models.CharField("Покрытие пола", max_length=120, choices=(("ковер", "ковер"), ("керамика", "керамика"), ("ламинат", "ламинат"),
                                                                        ("паркет", "паркет")), blank=True)
    room_clenaning = models.FloatField("Уборка комнаты/кол-во раз в неделю", blank=True, null=True)
    bed_linen_changing = models.FloatField("Замена белья/кол-во раз в неделю", blank=True, null=True)
    towel_changing = models.FloatField("Замена полотенец.кол-во раз в неделю", blank=True, null=True)
    ironing = models.CharField("Утюг и гладильная доска", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    room_service = models.CharField("Сервис в номер", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)

    beach_location = models.CharField("Расположение пляжа", max_length=120, choices=(("первая линия", "первая линия"),
                                                                                     ("через дорогу", "через дорогу"),
                                                                                     ("вторая линия", "вторая линия"),
                                               ("шаттл-бас до пляжа", "шаттл-бас до пляжа")), blank=True)
    beach_shattle = models.FloatField("Шаттл-бас/раз в неделю", blank=True, null=True)
    beach_location_m = models.CharField("Расстояние до пляжа, м", max_length=120, blank=True)
    beach_type = models.CharField("Частный/публичный", max_length=120, choices=(("частный", "частный"), ("публичный", "публичный")), blank=True)
    beach_sand = models.CharField("Покрытие пляжа", max_length=120, choices=(("песок", "песок"), ("галька", "галька"),
                                                                             ("песчано-галечный", "песчано-галечный")), blank=True)
    beach_length = models.CharField("Протяженность, м", max_length=120, blank=True)
    beach_towels = models.CharField("Пляжные полотенца", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    beach_towels_price = models.CharField("Цена за полотенца/день", max_length=120, blank=True)
    beach_umbrella = models.CharField("Пляжные зонты", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    beach_umbrella_price = models.CharField("Цена за зонты/день", max_length=120, blank=True)
    beach_mattres = models.CharField("Матрасы", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank = True)
    beach_mattres_price = models.CharField("Цена за матрасы/день", max_length=120, blank=True)
    beach_chaise_lounge = models.CharField("Шезлонги", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    beach_chaise_lounge_price = models.CharField("Цена за шезлонги/день", max_length=120, blank=True)
    beach_gazebo = models.CharField("Газебо", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    beach_gazebo_price = models.CharField("Цена за газебо/день", max_length=120, blank=True)

    restaurant_quntity = models.FloatField("Кол-во ресторанов", blank=True, null=True)
    main_restaurant_cusine = models.CharField("Главный ресторан, кухня", max_length=200, blank=True)
    main_restaurant_working_hours = models.TimeField("Главный ресторан, часы работы", blank=True, null=True)
    a_la_carte_quntity = models.FloatField("Кол-во A la Carte", blank=True, null=True)
    a_la_carte_free_quntity = models.FloatField("Из них бесплатных", blank=True, null=True)
    a_la_carte_restaurant_cusine = models.TextField("A la Carte рестораны: названия, кухня, часы работы", blank=True)
    bar_quntity = models.FloatField("Кол-во баров", blank=True, null=True)
    bar_choice = models.CharField("Бары", max_length=120, choices=(("бар на пляже", "бар на пляже"), ("бар у бассейна", "бар у бассейна"),
                                                                   ("лобби-бар", "лобби-бар"), ("кафе-бар", "кафе-бар"),
                 ("диско-бар", "диско-бар"), ("витамин-бар", "витамин-бар")), blank = True)
    bar_pool = models.FloatField("Кол-во баров у бассейна", blank=True, null=True)
    bar_beach = models.FloatField("Кол-во баров на пляже", blank=True, null=True)
    bar_cusine = models.TextField("Другие бары: названия, кухня, часы работы", blank=True)
    continental_breakfact = models.BooleanField("континентальный завтрак", blank=True, null=True)
    buffet_breakfast = models.BooleanField("завтрак-буфет", blank=True, null=True)
    late_breakfast = models.BooleanField("поздний завтрак", blank=True, null=True)
    lunch_buffet = models.BooleanField("ланч-буфет", blank=True, null=True)
    menu_lanch = models.BooleanField("ланч по меню", blank=True, null=True)
    sandwich_corner = models.BooleanField("уголок с сэндвичами", blank=True, null=True)
    coffee_and_desserts = models.BooleanField("кофе и пирожные", blank=True, null=True)
    dinner_buffet = models.BooleanField("обед-буфет", blank=True, null=True)
    dinner_menu = models.BooleanField("обед по меню", blank=True, null=True)
    late_dinner = models.BooleanField("поздний обед", blank=True, null=True)
    night_snacks = models.BooleanField("ночные снеки", blank=True, null=True)
    snacks_24_h = models.BooleanField("закуски 24 часа", blank=True, null=True)
    ice_cream = models.BooleanField("мороженое", blank=True, null=True)
    fresh = models.BooleanField("фреш", blank=True, null=True)
    soft_drinks = models.BooleanField("прохладительные напитки", blank=True, null=True)
    local_alkohol_drinks = models.BooleanField("местные алкогольные напитки", blank=True, null=True)
    imported_drinks = models.BooleanField("импортные алкогольные напитки", blank=True, null=True)
    barbeku = models.BooleanField("барбекю", blank=True, null=True)
    all_inclusive_working_hours = models.TimeField("Часы работы All Inclusive", blank=True, null=True)
    all_inclusive_pay = models.TextField("All Inclusive, платные услуги", blank=True)
    all_inclusive_mini_bar = models.BooleanField("Мини-бар включен в All Inclusive (бесплатно)", blank=True, null=True)
    all_inclusive_mini_bar_choice = models.CharField("Мини-бар, наполнение", max_length=200, blank=True)

    aerobics = models.BooleanField("аэробика", blank=True, null=True)
    aquaaerobics = models.BooleanField("аквааэробика", blank=True, null=True)
    basketball = models.BooleanField("баскетбол", blank=True, null=True)
    football = models.BooleanField("футбол", blank=True, null=True)
    volleyboll = models.BooleanField("воллейбол", blank=True, null=True)
    bocce = models.BooleanField("бочче", blank=True, null=True)
    mini_football = models.BooleanField("мини-футбол", blank=True, null=True)
    golf = models.BooleanField("гольф", blank=True, null=True)
    gym = models.BooleanField("тренажерный зал", blank=True, null=True)
    tennis_cort = models.BooleanField("теннисный корт", blank=True, null=True)
    table_tennis = models.BooleanField("настольный теннис", blank=True, null=True)
    animation = models.BooleanField("анимация", blank=True, null=True)
    children_animation = models.BooleanField("детская анимация", blank=True, null=True)
    live_music = models.BooleanField("живая музыка", blank=True, null=True)
    water_sport = models.TextField("Водные виды спорта (платно, перечислите)", blank=True)
    bicykle_rent = models.CharField("Аренда велосипедов", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank = True)
    billiard = models.CharField("Бильярд", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank = True)
    bowling = models.CharField("Боулинг", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank = True)
    casino = models.CharField("Казино", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank = True)
    katamarans = models.CharField("Аренда катамаранов", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank = True)
    cinema = models.CharField("Кинотеатр", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    disco = models.CharField("Дискотека", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")),blank=True)
    diving = models.CharField("Дайвинг", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    videogames = models.CharField("Видеоигры", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    jacuzzi = models.CharField("Джакузи", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    night_club = models.CharField("Ночной клуб", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    serfing = models.CharField("Серфинг", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    water_polo = models.CharField("Водное поло", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    tennis_equipment = models.CharField("Оборудование для тенниса", max_length=120, choices=(("бесплатно", "бесплатно"),
                                                                                             ("освещение платно", "освещение платно"),
                                                                                             ("оборудование платно", "оборудование платно")),
                                        blank = True)
    spa = models.CharField("SPA", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    massage = models.CharField("Массаж", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    spa_treatment = models.TextField("Услуги SPA-центра", blank=True)
    outdoor_swimming_pool = models.FloatField("Количество открытых бассейнов", blank=True, null=True)
    outdoor_swimming_pool_heating = models.FloatField("Кол-во открытых бассейнов с подогревом", blank=True, null=True)
    outdoor_swimming_pool_for_children = models.FloatField("Кол-во детских открытых бассейнов", blank=True, null=True)
    outdoor_swimming_pool_with_sea_water = models.FloatField("Кол-во открытых бассейнов с морской водой", blank=True, null=True)
    indoor_swimming_pool = models.FloatField("Количество закрытых бассейнов", blank=True, null=True)
    indoor_swimming_pool_heating = models.FloatField("Кол-во закрытых бассейнов с подогревом", blank=True, null=True)
    indoor_swimming_pool_for_children = models.FloatField("Кол-во детских закрытых бассейнов", blank=True, null=True)
    indoor_swimming_pool_with_sea_water = models.FloatField("Кол-во закрытых бассейнов с морской водой", blank=True, null=True)
    aquapark = models.CharField("Аквапарк", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    water_slides = models.FloatField("Кол-во водных горок", blank=True, null=True)

    beauty_salon = models.BooleanField("салон красоты", blank=True, null=True)
    hair_dresser = models.BooleanField("парикмахерская", blank=True, null=True)
    shop = models.BooleanField("магазин", blank=True, null=True)
    laundry = models.BooleanField("прачечная", blank=True, null=True)
    amphiteatre = models.BooleanField("амфитеатр", blank=True, null=True)
    atm = models.BooleanField("банкомат", blank=True, null=True)
    exchange = models.BooleanField("обмен валюты", blank=True, null=True)
    parking = models.BooleanField("парковка", blank=True, null=True)
    library = models.BooleanField("библиотека", blank=True, null=True)
    conference_room = models.CharField("Конференц-зал", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    conference_room_quantity = models.FloatField("Кол-во конференц-залов", blank=True, null=True)
    wi_fi_in_hotel = models.CharField("Wi-Fi на территории", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    wi_fi_in_hotel_price = models.FloatField("Цена Wi-Fi/день", blank=True, null=True)
    reception_safe = models.CharField("Сейф на ресепшен", max_length=120, choices=(("бесплатно", "бесплатно"), ("платно", "платно")), blank=True)
    reception_safe_price = models.FloatField("Цена сейф/день", blank=True, null=True)

    def __str__(self):
        return self.hotel_name



def create(self):
    hotel = Hotel_description()
    hotel.save()
