# Generated by Django 2.2.3 on 2019-08-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactSheet', '0002_auto_20190813_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_description',
            name='all_inclusive_working_hours',
            field=models.TimeField(blank=True, null=True, verbose_name='Часы работы All Inclusive'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='anex_floors',
            field=models.FloatField(blank=True, null=True, verbose_name='Anex, этажей'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='anex_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Anex, корпусов'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='bar_beach',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во баров на пляже'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='bar_pool',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во баров у бассейна'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='bar_quntity',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во баров'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='beach_shattle',
            field=models.FloatField(blank=True, null=True, verbose_name='Шаттл-бас/раз в неделю'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='bed_linen_changing',
            field=models.FloatField(blank=True, null=True, verbose_name='Замена белья/кол-во раз в неделю'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='check_in',
            field=models.TimeField(blank=True, max_length=50, null=True, verbose_name='Check in'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='check_out',
            field=models.TimeField(blank=True, max_length=50, null=True, verbose_name='Check out'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='distance_to_beach',
            field=models.FloatField(blank=True, null=True, verbose_name='До пляжа, м'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='indoor_swimming_pool',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество закрытых бассейнов'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='indoor_swimming_pool_for_children',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во детских закрытых бассейнов'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='indoor_swimming_pool_heating',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во закрытых бассейнов с подогревом'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='indoor_swimming_pool_with_sea_water',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во закрытых бассейнов с морской водой'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='main_building',
            field=models.FloatField(blank=True, null=True, verbose_name='Главное здание, этажей'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='other_buildings_floors',
            field=models.FloatField(blank=True, null=True, verbose_name='Доп. корпуса, этажей'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='other_buildings_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Доп. корпуса, кол-во'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='outdoor_swimming_pool',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество открытых бассейнов'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='outdoor_swimming_pool_for_children',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во детских открытых бассейнов'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='outdoor_swimming_pool_heating',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во открытых бассейнов с подогревом'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='outdoor_swimming_pool_with_sea_water',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во открытых бассейнов с морской водой'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='restaurant_quntity',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во ресторанов'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='room_clenaning',
            field=models.FloatField(blank=True, null=True, verbose_name='Уборка комнаты/кол-во раз в неделю'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='room_type_numbers',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во номеров этого типа'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='room_type_rooms',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество комнат в номере'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='room_type_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер, кв.м.'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='total_room_numbers',
            field=models.FloatField(null=True, verbose_name='Общее количество номеров'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='towel_changing',
            field=models.FloatField(blank=True, null=True, verbose_name='Замена полотенец.кол-во раз в неделю'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='tv_channels',
            field=models.FloatField(blank=True, null=True, verbose_name='Русских каналов'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='villas_floors',
            field=models.FloatField(blank=True, null=True, verbose_name='Виллы, этажей'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='villas_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Виллы, кол-во'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='water_slides',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во водных горок'),
        ),
    ]
