# Generated by Django 2.2.3 on 2019-08-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactSheet', '0003_auto_20190813_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_description',
            name='adults_only',
            field=models.BooleanField(blank=True, null=True, verbose_name='Только для взрослых'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='aerobics',
            field=models.BooleanField(blank=True, null=True, verbose_name='аэробика'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='all_inclusive_mini_bar',
            field=models.BooleanField(blank=True, null=True, verbose_name='Мини-бар включен в All Inclusive (бесплатно)'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='amphiteatre',
            field=models.BooleanField(blank=True, null=True, verbose_name='амфитеатр'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='animation',
            field=models.BooleanField(blank=True, null=True, verbose_name='анимация'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='aquaaerobics',
            field=models.BooleanField(blank=True, null=True, verbose_name='аквааэробика'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='atm',
            field=models.BooleanField(blank=True, null=True, verbose_name='банкомат'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='barbeku',
            field=models.BooleanField(blank=True, null=True, verbose_name='барбекю'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='basketball',
            field=models.BooleanField(blank=True, null=True, verbose_name='баскетбол'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='beauty_salon',
            field=models.BooleanField(blank=True, null=True, verbose_name='салон красоты'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='bocce',
            field=models.BooleanField(blank=True, null=True, verbose_name='бочче'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='buffet_breakfast',
            field=models.BooleanField(blank=True, null=True, verbose_name='завтрак-буфет'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='children_animation',
            field=models.BooleanField(blank=True, null=True, verbose_name='детская анимация'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='coffee_and_desserts',
            field=models.BooleanField(blank=True, null=True, verbose_name='кофе и пирожные'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='coffee_and_tea',
            field=models.BooleanField(blank=True, null=True, verbose_name='Наборы для чая и кофе'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='conference_room_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во конференц-залов'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='connected_rooms',
            field=models.BooleanField(blank=True, null=True, verbose_name='Cовмещенные комнаты'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='continental_breakfact',
            field=models.BooleanField(blank=True, null=True, verbose_name='континентальный завтрак'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='dinner_buffet',
            field=models.BooleanField(blank=True, null=True, verbose_name='обед-буфет'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='dinner_menu',
            field=models.BooleanField(blank=True, null=True, verbose_name='обед по меню'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='disabled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Услуги для инвалидов'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='dishes',
            field=models.BooleanField(blank=True, null=True, verbose_name='Тарелки и столовые приборы'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='dishwasher',
            field=models.BooleanField(blank=True, null=True, verbose_name='Посудомоечная машина'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='door_rooms',
            field=models.BooleanField(blank=True, null=True, verbose_name='Дверь между комнатами'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='dvd',
            field=models.BooleanField(blank=True, null=True, verbose_name='DVD'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='exchange',
            field=models.BooleanField(blank=True, null=True, verbose_name='обмен валюты'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='football',
            field=models.BooleanField(blank=True, null=True, verbose_name='футбол'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='fresh',
            field=models.BooleanField(blank=True, null=True, verbose_name='фреш'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='fridge',
            field=models.BooleanField(blank=True, null=True, verbose_name='Холодильник'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='golf',
            field=models.BooleanField(blank=True, null=True, verbose_name='гольф'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='gym',
            field=models.BooleanField(blank=True, null=True, verbose_name='тренажерный зал'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='hair_dresser',
            field=models.BooleanField(blank=True, null=True, verbose_name='парикмахерская'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='hair_dryer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Фен'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='ice_cream',
            field=models.BooleanField(blank=True, null=True, verbose_name='мороженое'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='imported_drinks',
            field=models.BooleanField(blank=True, null=True, verbose_name='импортные алкогольные напитки'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='jakuzi',
            field=models.BooleanField(blank=True, null=True, verbose_name='Джакузи'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='ketler',
            field=models.BooleanField(blank=True, null=True, verbose_name='Чайник'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='late_breakfast',
            field=models.BooleanField(blank=True, null=True, verbose_name='поздний завтрак'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='late_dinner',
            field=models.BooleanField(blank=True, null=True, verbose_name='поздний обед'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='laundry',
            field=models.BooleanField(blank=True, null=True, verbose_name='прачечная'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='library',
            field=models.BooleanField(blank=True, null=True, verbose_name='библиотека'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='live_music',
            field=models.BooleanField(blank=True, null=True, verbose_name='живая музыка'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='living_room',
            field=models.BooleanField(blank=True, null=True, verbose_name='Есть гостиная'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='local_alkohol_drinks',
            field=models.BooleanField(blank=True, null=True, verbose_name='местные алкогольные напитки'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='lunch_buffet',
            field=models.BooleanField(blank=True, null=True, verbose_name='ланч-буфет'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='menu_lanch',
            field=models.BooleanField(blank=True, null=True, verbose_name='ланч по меню'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='microwave',
            field=models.BooleanField(blank=True, null=True, verbose_name='Микроволновка'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='mini_bar',
            field=models.BooleanField(blank=True, null=True, verbose_name='Мини-бар'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='mini_football',
            field=models.BooleanField(blank=True, null=True, verbose_name='мини-футбол'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='mini_kitchen',
            field=models.BooleanField(blank=True, null=True, verbose_name='Мини-кухня'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='night_snacks',
            field=models.BooleanField(blank=True, null=True, verbose_name='ночные снеки'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='non_smoking_hotel',
            field=models.BooleanField(blank=True, null=True, verbose_name='Курение на всей территории запрещено'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='oven',
            field=models.BooleanField(blank=True, null=True, verbose_name='Плита с духовкой'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='parking',
            field=models.BooleanField(blank=True, null=True, verbose_name='парковка'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='pets_friendly',
            field=models.BooleanField(blank=True, null=True, verbose_name='Размещение с домашними животными'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='reception_safe_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена сейф/день'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='roba_and_slippers',
            field=models.BooleanField(blank=True, null=True, verbose_name='Халаты и тапочки'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='sandwich_corner',
            field=models.BooleanField(blank=True, null=True, verbose_name='уголок с сэндвичами'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='shop',
            field=models.BooleanField(blank=True, null=True, verbose_name='магазин'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='snacks_24_h',
            field=models.BooleanField(blank=True, null=True, verbose_name='закуски 24 часа'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='soft_drinks',
            field=models.BooleanField(blank=True, null=True, verbose_name='прохладительные напитки'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='table_tennis',
            field=models.BooleanField(blank=True, null=True, verbose_name='настольный теннис'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='telephone_in_room',
            field=models.BooleanField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='tennis_cort',
            field=models.BooleanField(blank=True, null=True, verbose_name='теннисный корт'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='terrace',
            field=models.BooleanField(blank=True, null=True, verbose_name='Терраса'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='tv',
            field=models.BooleanField(blank=True, null=True, verbose_name='TV'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='volleyboll',
            field=models.BooleanField(blank=True, null=True, verbose_name='воллейбол'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='wi_fi_in_hotel_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена Wi-Fi/день'),
        ),
    ]
