# Generated by Django 2.2.3 on 2019-08-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactSheet', '0004_auto_20190813_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_description',
            name='adults_only_age',
            field=models.FloatField(blank=True, null=True, verbose_name='Минимальный возраст гостей (для отелей adults only)'),
        ),
    ]
