# Generated by Django 2.2.3 on 2019-08-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactSheet', '0005_auto_20190813_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_description',
            name='child_pool_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество детских бассейнов'),
        ),
    ]
