# Generated by Django 2.2.3 on 2019-08-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactSheet', '0008_auto_20190813_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_description',
            name='category',
            field=models.CharField(choices=[(1, '3* '), (2, '4* '), (3, '5* '), (4, '- ')], max_length=50, null=True, verbose_name='Звездность'),
        ),
        migrations.AlterField(
            model_name='hotel_description',
            name='meal',
            field=models.CharField(choices=[(1, 'BB'), (2, 'HB'), (3, 'FB'), (4, 'All Inclusive')], max_length=50, null=True, verbose_name='Тип питания'),
        ),
    ]
